# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:5000/
Accept: application/json

###

GET http://localhost:5000/company
Accept: application/json

###

GET http://localhost:5000/client
Accept: application/json

###

GET http://localhost:5000/staff
Accept: application/json

###

GET http://localhost:5000/status
Accept: application/json

###

GET http://localhost:5000/project
Accept: application/json

###

GET http://localhost:5000/job
Accept: application/json

###

GET http://localhost:5000/invoice
Accept: application/json

###

GET http://localhost:5000/company/1
Accept: application/json

###

GET http://localhost:5000/client/1
Accept: application/json

###

GET http://localhost:5000/staff/1
Accept: application/json

###

GET http://localhost:5000/status/1
Accept: application/json

###

GET http://localhost:5000/project/1
Accept: application/json

###

GET http://localhost:5000/job/1
Accept: application/json

###

GET http://localhost:5000/invoice/1
Accept: application/json

###

POST http://localhost:5000/company
Content-Type: application/json

{"name": "A Company Name", "address": "A Street"}

###

POST http://localhost:5000/client
Content-Type: application/json

{"telephone": "07010101010", "email": "client.name@example.com", "company_id": 1, "fullname": ""}

###

POST http://localhost:5000/staff
Content-Type: application/json

{"first_name": "Jane", "last_name": "Summer", "job_title": "Lackey", "rate": 5.0}

###

POST http://localhost:5000/status
Content-Type: application/json

{"title": "Started", "colour": "light-green"}

###

POST http://localhost:5000/project
Content-Type: application/json

{"client_id": 2}

###

POST http://localhost:5000/job
Content-Type: application/json

{"project_id": 4, "status_id": 1, "title": "A Job Name", "description": "Do this job", "assigned_to": 1, "estimated_time": 8.0, "deadline": "2018-09-26"}

###

PUT http://localhost:5000/company/1
Content-Type: application/json

{"name": "A New Company Name", "address": "A Street"}

###

PUT http://localhost:5000/client/1
Content-Type: application/json

{"telephone": "07020202020", "email": "new.client.name@example.com", "company_id": 1, "fullname": "New Client Name"}

###

PUT http://localhost:5000/staff/1
Content-Type: application/json

{"first_name": "Jane", "last_name": "Spring", "job_title": "Manager", "rate": 8.0}

###

PUT http://localhost:5000/status/1
Content-Type: application/json

{"title": "Has Started", "colour": "light-blue"}

###

PUT http://localhost:5000/project/1
Content-Type: application/json

{"client_id": 1}

###

PUT http://localhost:5000/job/1
Content-Type: application/json

{"project_id": 4, "status_id": 1, "title": "A New Job Name", "description": "Do this job now", "assigned_to": 2, "estimated_time": 12.0, "deadline": "2018-09-26"}

###

DELETE http://localhost:5000/company/
Accept: application/json

###

DELETE http://localhost:5000/client/3
Accept: application/json

###

DELETE http://localhost:5000/staff/3
Accept: application/json

###

DELETE http://localhost:5000/status/3
Accept: application/json

###

DELETE http://localhost:5000/project/3
Accept: application/json

###

DELETE http://localhost:5000/job/3
Accept: application/json

###